# Generated by Django 4.1 on 2022-08-22 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MusicAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Storeroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_type', models.CharField(choices=[(1, 'CD'), (2, 'Vinyl'), (3, 'Cassette')], max_length=128)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_amount', to='lajkacorp.musicalbum')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_message', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField()),
                ('income', models.IntegerField(default=0)),
                ('month', models.IntegerField(default='08')),
                ('year', models.IntegerField(default='2022')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_income', to='lajkacorp.musicalbum')),
                ('chanel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distro_income', to='lajkacorp.distribution')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistIncomeSpliter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_of_income', models.FloatField()),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inc_spliter', to='lajkacorp.income')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inc_split', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
