# Generated by Django 4.1 on 2022-08-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lajkacorp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistincomespliter',
            old_name='income',
            new_name='income_on',
        ),
        migrations.AlterField(
            model_name='income',
            name='month',
            field=models.CharField(choices=[('Styczeń', 'Styczeń'), ('Luty', 'Luty'), ('Marzec', 'Marzec'), ('Kwiecień', 'Kwiecień'), ('Maj', 'Maj'), ('Czerwiec', 'Czerwiec'), ('Lipiec', 'Lipiec'), ('Sierpień', 'Sierpień'), ('Wrzesień', 'Wrzesień'), ('Październik', 'Październik'), ('Listopad', 'Listopad'), ('Grudzień', 'Grudzień')], default='styczeń', max_length=64),
        ),
        migrations.AlterField(
            model_name='storeroom',
            name='carrier_type',
            field=models.CharField(choices=[('CD', 'CD'), ('Vinyl', 'Vinyl'), ('Cassette', 'Cassette')], max_length=64),
        ),
    ]
