# Generated by Django 4.1 on 2022-08-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lajkacorp', '0002_rename_income_artistincomespliter_income_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='styczeń', max_length=64),
        ),
    ]
